// generated by @ver5/vite-plugin-utools
// DO NOT CHANGE THIS FILE!
/// <reference types="@ver5/vite-plugin-utools/utools" />

interface Window {
  services: {
    IconMap: typeof import('./preload')['IconMap']
    clearClipboard: typeof import('./preload')['clearClipboard']
    decryptValue: typeof import('./preload')['decryptValue']
    encryptValue: typeof import('./preload')['encryptValue']
    exportFile: typeof import('./preload')['exportFile']
    getKeyIv: typeof import('./preload')['getKeyIv']
    keepass: typeof import('./preload')['keepass']
    readBuffer: typeof import('./preload')['readBuffer']
    selectFile2Import: typeof import('./preload')['selectFile2Import']
    totp: typeof import('./preload')['totp']
  }
}